version: '3'
name: shopping_mall
services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway:gateway
    ports:
      - 8080:8080
    extra_hosts:
      - "localhost:host-gateway"

  order_management:
    build:
      context: ./order_management
      dockerfile: Dockerfile
    image: order_management:order_management
    ports:
      - 8083:8083
    extra_hosts:
      - "localhost:host-gateway"

# networks:
#   network:
#     driver: bridge