version: '3'
# name: shopping_mall # name does not work in Jenkins
services:
  redis:
    image: redis:latest
    container_name: redis
    # command: redis-server --appendonly yes
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    ports:
      - '6379:6379'
    volumes:
      - '/redis_data:/redis_data'
    networks:
      - myNetwork
    # extra_hosts: # does not work
    #   - "localhost:host-gateway"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: gateway:gateway
    container_name: gateway
    ports:
      - 8080:8080
    extra_hosts:
      - "localhost:host-gateway"

  user_management:
    build:
      context: ./user_management
      dockerfile: Dockerfile
    image: user_management:user_management
    container_name: user_management
    ports:
      - 8082:8082
    # depends_on:
    #   - redis
    networks:
      - myNetwork
    extra_hosts:
      - "localhost:host-gateway"

networks:
  myNetwork:
    driver: bridge
    # external: true