version: '3'
# name: shopping_mall # name does not work in Jenkins
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    # command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - '6379:6379'
    expose:
      - '6379'
    volumes:
      - '/redis_data:/redis_data'
    networks:
      - myNetwork
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 3

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    image: gateway:gateway
    container_name: gateway
    ports:
      - 8080:8080
    extra_hosts:
      - "localhost:host-gateway"

  order_management:
    build:
      context: ../order_management
      dockerfile: Dockerfile
    image: order_management:order_management
    container_name: order_management
    ports:
      - 8081:8081
    extra_hosts:
      - "localhost:host-gateway"

  user_management:
    build:
      context: ../user_management
      dockerfile: Dockerfile
    image: user_management:user_management
    container_name: user_management
    ports:
      - 8082:8082
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - myNetwork

  product_management:
    build:
      context: ../product_management
      dockerfile: Dockerfile
    image: product_management:product_management
    container_name: product_management
    ports:
      - 8083:8083
    extra_hosts:
      - "localhost:host-gateway"

  notification:
    build:
      context: ../notification
      dockerfile: Dockerfile
    image: notification:notification
    container_name: notification
    ports:
      - 8084:8084
    extra_hosts:
      - "localhost:host-gateway"

networks:
  myNetwork:
    driver: bridge