spring:
  cloud:
    gateway:
      routes:
      - id: order_management
        uri: http://${orderManagement:localhost}:8081
        predicates:
        - Path=/orderManagement/**
        filters:
        - RewritePath=/orderManagement/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
      - id: user_management
        uri: http://${userManagement:localhost}:8082
        predicates:
        - Path=/userManagement/**
        filters:
        - RewritePath=/userManagement/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
      - id: productManagement
        uri: http://${productManagement:localhost}:8083
        predicates:
        - Path=/productManagement/**
        filters:
        - RewritePath=/productManagement/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
      - id: notification
        uri: http://${notification:localhost}:8084
        predicates:
        - Path=/notification/**
        filters:
        - RewritePath=/notification/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
